"""Initial migration

Revision ID: 20251024_initial
Revises: 
Create Date: 2025-10-24 11:20:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '20251024_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('wallet_address', sqlmodel.sql.sqltypes.AutoString(length=42), nullable=False),
    sa.Column('webhook_uuid', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('encrypted_webhook_secret', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('dydx_address', sqlmodel.sql.sqltypes.AutoString(length=43), nullable=True),
    sa.Column('encrypted_dydx_private_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('encrypted_telegram_token', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('encrypted_telegram_chat_id', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('wallet_address'),
    sa.UniqueConstraint('webhook_uuid')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_address', sqlmodel.sql.sqltypes.AutoString(length=42), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('size', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('dydx_order_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('tp_order_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('sl_order_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_address'], ['users.wallet_address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_address'], ['users.wallet_address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('side', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('fee', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('webhook_events')
    op.drop_table('positions')
    op.drop_table('users')
    # ### end Alembic commands ###
